apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-pet-clinic-pod-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-pet-clinic-pod-v2
      track: blue
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: gke-pet-clinic-pod-v2
        track: blue
    spec:
      containers:
      - name: gke-pet-clinic-pod
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 8080
        env:
          - name: "POD_RELEASE"
            value: "blue"
        readinessProbe:
          httpGet:
             path: /actuator/health
             port: 8080
          failureThreshold: 6
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 6
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1