apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-pet-clinic-pod-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-pet-clinic-pod-v2
      track: blue
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: gke-pet-clinic-pod-v2
        track: blue
    spec:
      containers:
      - name: gke-pet-clinic-pod
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m