apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-pet-clinic-pod-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gke-pet-clinic-pod-v1
      track: green
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 8
  template:
    metadata:
      labels:
        app: gke-pet-clinic-pod-v1
        track: green
    spec:
      containers:
      - name: gke-pet-clinic-pod
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m